# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15RkXDPOciZkmwUzNMew5PtK-Ighw7Y8O
"""

import streamlit as st
import joblib
import numpy as np
import pandas as pd

# Load the trained model
model = joblib.load('improved_gbr_model.pkl')

# App title
st.title("Sales Prediction App")

# User input features
st.sidebar.header("Input Features")
n_estimators = st.sidebar.number_input("Number of Estimators", min_value=100, max_value=300, value=200, step=10)
max_depth = st.sidebar.number_input("Max Depth", min_value=3, max_value=7, value=5)
learning_rate = st.sidebar.slider("Learning Rate", min_value=0.01, max_value=0.2, value=0.1, step=0.01)

# Input features from user
user_input = st.text_input("Enter feature values (comma-separated):")
if user_input:
    try:
        features = np.array([float(i) for i in user_input.split(",")]).reshape(1, -1)
        prediction = model.predict(features)
        st.write(f"Predicted Value: {prediction[0]:.2f}")
    except Exception as e:
        st.error("Invalid input! Please enter comma-separated numeric values.")

# Model details
if st.checkbox("Show Model Details"):
    st.write("Best Parameters:", model.get_params())